public class SelectionSortAnimationWindow extends com.cim.AIA.AnimationWindow {
    final private static long serialVersionUID = -7476859979873128117L;
    final protected static String QUIZ_FILE_NAME = "selectionsort.quiz";
    final protected static String BUILD_DATE = "10 June 99";
    final protected static String BUILD_BY = "T.Witham";
    final protected static String FRAME_TITLE;
    final public static int[] DEFAULT_DATA;
    final public static int[] SORTED_DATA;
    final public static int[] REVERSE_SORTED_DATA;
    protected int minimumNumberOfElements;
    protected int maximumNumberOfElements;
    protected int maxSize;
    protected int minSize;
    
    public String getAlgorithmName()
    {
        return "AIA: SelectionSort";
    }
    
    public SelectionSortAnimationWindow(com.cim.AIA.AlgorithmCanvas a, com.cim.AIA.AlgorithmThread a0, java.applet.Applet a1)
    {
        super(a, a0, a1);
        this.minimumNumberOfElements = 3;
        this.maximumNumberOfElements = 20;
        this.maxSize = 99;
        this.minSize = 1;
        this.buildDate = "10 June 99";
        this.buildBy = "T.Witham";
        String s = SelectionSortAnimationWindow.FRAME_TITLE;
        this.frameTitle = s;
        StringBuilder a2 = new StringBuilder();
        String s0 = SelectionSortAnimationWindow.QUIZ_MODE_LABEL;
        StringBuilder a3 = a2.append(s0);
        StringBuilder a4 = a3.append("...");
        String s1 = a4.toString();
        String s2 = localization.Messages.getString("SelectionSortAnimationWindow.1");
        StringBuilder a5 = new StringBuilder();
        java.net.URL a6 = a1.getCodeBase();
        String s3 = a6.toString();
        StringBuilder a7 = a5.append(s3);
        StringBuilder a8 = a7.append("images/");
        String s4 = a8.toString();
        com.cim.AIA.QuizModeSelection a9 = new com.cim.AIA.QuizModeSelection(s1, false, (com.cim.AIA.AnimationWindow)this, a0, a1, s2, "selectionsort.quiz", s4, "correct.gif", "incorrect.gif");
        this.addModeSelection((com.cim.AIA.ModeSelection)a9);
        String s5 = SelectionSortAnimationWindow.DEFAULT_LABEL;
        int[] a10 = SelectionSortAnimationWindow.DEFAULT_DATA;
        com.cim.AIA.PresetIntArrayDataSelection a11 = new com.cim.AIA.PresetIntArrayDataSelection(s5, true, (com.cim.AIA.AnimationWindow)this, a10);
        this.addDataSelection((com.cim.AIA.DataSelection)a11);
        String s6 = SelectionSortAnimationWindow.SORTED_LABEL;
        int[] a12 = SelectionSortAnimationWindow.SORTED_DATA;
        com.cim.AIA.PresetIntArrayDataSelection a13 = new com.cim.AIA.PresetIntArrayDataSelection(s6, false, (com.cim.AIA.AnimationWindow)this, a12);
        this.addDataSelection((com.cim.AIA.DataSelection)a13);
        String s7 = SelectionSortAnimationWindow.REVERSE_SORTED_LABEL;
        int[] a14 = SelectionSortAnimationWindow.REVERSE_SORTED_DATA;
        com.cim.AIA.PresetIntArrayDataSelection a15 = new com.cim.AIA.PresetIntArrayDataSelection(s7, false, (com.cim.AIA.AnimationWindow)this, a14);
        this.addDataSelection((com.cim.AIA.DataSelection)a15);
        String s8 = SelectionSortAnimationWindow.SAME_LABEL;
        int i = this.minimumNumberOfElements;
        int i0 = this.maximumNumberOfElements;
        int i1 = this.minSize;
        int i2 = this.maxSize;
        com.cim.AIA.RandomSameIntArrayDataSelection a16 = new com.cim.AIA.RandomSameIntArrayDataSelection(s8, false, (com.cim.AIA.AnimationWindow)this, i, i0, i1, i2);
        this.addDataSelection((com.cim.AIA.DataSelection)a16);
        String s9 = SelectionSortAnimationWindow.RANDOM_LABEL;
        int i3 = this.minimumNumberOfElements;
        int i4 = this.maximumNumberOfElements;
        int i5 = this.minSize;
        int i6 = this.maxSize;
        com.cim.AIA.RandomIntArrayDataSelection a17 = new com.cim.AIA.RandomIntArrayDataSelection(s9, false, (com.cim.AIA.AnimationWindow)this, i3, i4, i5, i6);
        this.addDataSelection((com.cim.AIA.DataSelection)a17);
        StringBuilder a18 = new StringBuilder();
        String s10 = SelectionSortAnimationWindow.USER_SELECTION_LABEL;
        StringBuilder a19 = a18.append(s10);
        StringBuilder a20 = a19.append("...");
        String s11 = a20.toString();
        String s12 = SelectionSortAnimationWindow.USER_SELECTION_LABEL;
        int i7 = this.minSize;
        int i8 = this.maxSize;
        int i9 = this.minimumNumberOfElements;
        int i10 = this.maximumNumberOfElements;
        com.cim.AIA.UserSelectionIntArrayDataSelection a21 = new com.cim.AIA.UserSelectionIntArrayDataSelection(s11, false, (com.cim.AIA.AnimationWindow)this, s12, i7, i8, i9, i10);
        this.addDataSelection((com.cim.AIA.DataSelection)a21);
        String s13 = com.cim.AIA.AnimationWindow.STEP_LABEL;
        String s14 = com.cim.AIA.AnimationWindow.STEP_INSTRUCTIONS;
        com.cim.AIA.StepButton a22 = new com.cim.AIA.StepButton(s13, s14, (com.cim.AIA.Controlable)this, a0);
        this.addControlButton((com.cim.AIA.ControlButton)a22);
        String s15 = com.cim.AIA.AnimationWindow.BACK_LABEL;
        String s16 = com.cim.AIA.AnimationWindow.BACK_INSTRUCTIONS;
        com.cim.AIA.BackButton a23 = new com.cim.AIA.BackButton(s15, s16, (com.cim.AIA.Controlable)this, a0);
        this.addControlButton((com.cim.AIA.ControlButton)a23);
        String s17 = com.cim.AIA.AnimationWindow.RUN_LABEL;
        String s18 = com.cim.AIA.AnimationWindow.RUN_INSTRUCTIONS;
        com.cim.AIA.RunButton a24 = new com.cim.AIA.RunButton(s17, s18, (com.cim.AIA.Controlable)this, a0);
        this.addControlButton((com.cim.AIA.ControlButton)a24);
        String s19 = com.cim.AIA.AnimationWindow.PAUSE_LABEL;
        String s20 = com.cim.AIA.AnimationWindow.PAUSE_INSTRUCTIONS;
        com.cim.AIA.PauseButton a25 = new com.cim.AIA.PauseButton(s19, s20, (com.cim.AIA.Controlable)this, a0);
        this.addControlButton((com.cim.AIA.ControlButton)a25);
        String s21 = com.cim.AIA.AnimationWindow.RESET_LABEL;
        String s22 = com.cim.AIA.AnimationWindow.RESET_INSTRUCTIONS;
        com.cim.AIA.ResetButton a26 = new com.cim.AIA.ResetButton(s21, s22, (com.cim.AIA.AnimationWindow)this, a0);
        this.addControlButton((com.cim.AIA.ControlButton)a26);
    }
    
    static
    {
        String s = localization.Messages.getString("SelectionSortAnimationWindow.0");
        SelectionSortAnimationWindow.FRAME_TITLE = s;
        int[] a = new int[15];
        a[0] = 40;
        a[1] = 35;
        a[2] = 45;
        a[3] = 30;
        a[4] = 50;
        a[5] = 25;
        a[6] = 55;
        a[7] = 20;
        a[8] = 60;
        a[9] = 15;
        a[10] = 65;
        a[11] = 10;
        a[12] = 70;
        a[13] = 5;
        a[14] = 75;
        SelectionSortAnimationWindow.DEFAULT_DATA = a;
        int[] a0 = new int[15];
        a0[0] = 5;
        a0[1] = 10;
        a0[2] = 15;
        a0[3] = 20;
        a0[4] = 25;
        a0[5] = 30;
        a0[6] = 35;
        a0[7] = 40;
        a0[8] = 45;
        a0[9] = 50;
        a0[10] = 55;
        a0[11] = 60;
        a0[12] = 65;
        a0[13] = 70;
        a0[14] = 75;
        SelectionSortAnimationWindow.SORTED_DATA = a0;
        int[] a1 = new int[15];
        a1[0] = 75;
        a1[1] = 70;
        a1[2] = 65;
        a1[3] = 60;
        a1[4] = 55;
        a1[5] = 50;
        a1[6] = 45;
        a1[7] = 40;
        a1[8] = 35;
        a1[9] = 30;
        a1[10] = 25;
        a1[11] = 20;
        a1[12] = 15;
        a1[13] = 10;
        a1[14] = 5;
        SelectionSortAnimationWindow.REVERSE_SORTED_DATA = a1;
    }
}